### ISSUE TITLE
Hide thumbnail title

### ISSUE THREAD

**Issue by Athanaseus** [ratt-ru/radiopadre#95] opened 2020-09-23 13:57 UTC
I'm trying to hide the title on the displayed thumbnail with `title=False` \ `titles=False` but it still shows.

![Screenshot from 2020-09-23 15-53-29](https://user-images.githubusercontent.com/16665629/94022378-54b0c400-fdb5-11ea-87f6-96a8d0ad4985.png)

**Comment by o-smirnov** [comment] 2020-09-25 12:33
Duplicate of #94. I just realized this feature is too new, you need to be running the ``b1.0.x`` branch of radiopadre for it.

**Closed by o-smirnov** 2020-09-25 12:33 UTC
